# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'monedero.ui'
#
# Created: Fri May 30 14:14:58 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(803, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_apunte = QtGui.QPushButton(self.centralwidget)
        self.pushButton_apunte.setObjectName(_fromUtf8("pushButton_apunte"))
        self.horizontalLayout.addWidget(self.pushButton_apunte)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_3.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pushButton_5 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pushButton_8 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_4.addWidget(self.pushButton_8)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_apuntes = QtGui.QWidget()
        self.page_apuntes.setObjectName(_fromUtf8("page_apuntes"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_apuntes)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.page_apuntes)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tableWidget = QtGui.QTableWidget(self.groupBox_4)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.combo_orden = QtGui.QComboBox(self.page_apuntes)
        self.combo_orden.setObjectName(_fromUtf8("combo_orden"))
        self.combo_orden.addItem(_fromUtf8(""))
        self.combo_orden.addItem(_fromUtf8(""))
        self.combo_orden.addItem(_fromUtf8(""))
        self.combo_orden.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combo_orden)
        self.combo_T = QtGui.QComboBox(self.page_apuntes)
        self.combo_T.setObjectName(_fromUtf8("combo_T"))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.combo_T.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combo_T)
        self.combo_cuenta = QtGui.QComboBox(self.page_apuntes)
        self.combo_cuenta.setObjectName(_fromUtf8("combo_cuenta"))
        self.combo_cuenta.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combo_cuenta)
        self.combo_signo = QtGui.QComboBox(self.page_apuntes)
        self.combo_signo.setObjectName(_fromUtf8("combo_signo"))
        self.combo_signo.addItem(_fromUtf8(""))
        self.combo_signo.addItem(_fromUtf8(""))
        self.combo_signo.addItem(_fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.combo_signo)
        self.lineEdit = QtGui.QLineEdit(self.page_apuntes)
        self.lineEdit.setInputMask(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.stackedWidget.addWidget(self.page_apuntes)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Monedero", None))
        self.pushButton_apunte.setText(_translate("MainWindow", "+ Apunte", None))
        self.groupBox.setTitle(_translate("MainWindow", "Cuentas", None))
        self.pushButton_4.setText(_translate("MainWindow", "Resumenes", None))
        self.pushButton_3.setText(_translate("MainWindow", "Apuntes", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Extras", None))
        self.pushButton_5.setText(_translate("MainWindow", "Deudas", None))
        self.pushButton_6.setText(_translate("MainWindow", "Listas de la compra", None))
        self.pushButton_7.setText(_translate("MainWindow", "Garantias", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Configuración", None))
        self.pushButton_8.setText(_translate("MainWindow", "Configuración", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Ingresos y gastos de hoy", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fecha", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Concepto", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Vendedor / pagador", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cantidad", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Saldo", None))
        self.combo_orden.setItemText(0, _translate("MainWindow", "Más recientes", None))
        self.combo_orden.setItemText(1, _translate("MainWindow", "Más antiguos", None))
        self.combo_orden.setItemText(2, _translate("MainWindow", "Mayor importe", None))
        self.combo_orden.setItemText(3, _translate("MainWindow", "Menor importe", None))
        self.combo_T.setItemText(0, _translate("MainWindow", "Hoy", None))
        self.combo_T.setItemText(1, _translate("MainWindow", "Esta semana", None))
        self.combo_T.setItemText(2, _translate("MainWindow", "Últimos 7 dias", None))
        self.combo_T.setItemText(3, _translate("MainWindow", "Este mes", None))
        self.combo_T.setItemText(4, _translate("MainWindow", "Últimos 30 dias", None))
        self.combo_T.setItemText(5, _translate("MainWindow", "Este año", None))
        self.combo_T.setItemText(6, _translate("MainWindow", "Todo", None))
        self.combo_cuenta.setItemText(0, _translate("MainWindow", "Todas las cuentas", None))
        self.combo_signo.setItemText(0, _translate("MainWindow", "Ingresos y gastos", None))
        self.combo_signo.setItemText(1, _translate("MainWindow", "Ingresos", None))
        self.combo_signo.setItemText(2, _translate("MainWindow", "Gastos", None))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Filtro de texto", None))

